task: fix compile on gcc
GCC does not like the evaluation of `set_value_t(void)` in the
completion signature determination.  Promote this to a
type-specialization using concepts instead of the std::conditional
to appease GCC.

The compile failure was as follows:
```
task.hpp:370:17: error: invalid parameter type ‘void’
  370 |     friend auto tag_invoke(std::execution::get_completion_signatures_t,
      |                 ^~~~~~~~~~
task.hpp:370:17: error: in declaration ‘std::conditional_t<is_void_v<_Ty>, stdexec::completion_signatures<stdexec::__receivers::set_value_t(), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr), stdexec::__receivers::set_stopped_t()>, stdexec::completion_signatures<stdexec::__receivers::set_value_t(_Ty), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr), stdexec::__receivers::set_stopped_t()> > exec::__task::tag_invoke(stdexec::__get_completion_signatures::get_completion_signatures_t, const basic_task<_Ty, _Context>&, auto:82)’
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>