gcc: fix unused-parameter warning
error: unused parameter ‘__data’ [-Werror=unused-parameter]

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>