Add -Wno-c2y-extensions to test/CMakeLists.txt
As of some recent commit, building the tests with Clang 22.1 fails with
errors like this:
```
git/stdexec/test/stdexec/cpos/test_cpo_start.cpp:70:3: error: '__COUNTER__' is a
C2y extension [-Werror,-Wc2y-extensions]
   70 |   TEST_CASE("can call start on an operation state", "[cpo][cpo_start]")
      |   ^
```

Adding `-Wno-c2y-extensions` (or variations, like `-Wno-pedantic`) to
the `-DCMAKE_CXX_FLAGS` config-time parameters doesn't seems to help;
the flags added there end up *before* `-Wpedantic` in the compiler
command line, and, possibly because of llvm/llvm-project#184250, Clang
doesn't override `-Wpedantic` with an earlier-supplied suppression.

This diff just adds the required warning in the required place in the
hard-coded compiler warning flags to suppress the warning for everyone.

(https://github.com/llvm/llvm-project/issues/184250)