use std::size_t over size_t
Since the implementation is defined in the _P2300 namespace, it does
not have direct access to `std::size_t` through its own namespace.
Depending on the include order you can end up with compile errors.

```cpp
 #include "include/__utility.hpp"

 int main() { return 0; }
```

```
In file included from foo.cpp:1:
include/__utility.hpp:52:13: error: ‘size_t’ has not been declared
   52 |   template <size_t _N>
      |             ^~~~~~
include/__utility.hpp:53:44: error: ‘size_t’ was not declared in this scope; did you mean ‘std::size_t’?
   53 |     using __index = std::integral_constant<size_t, _N>;
      |                                            ^~~~~~
      |                                            std::size_t
...
```

Rather than trying to use the global namespace typedef, explicitly
select `std::size_t` whenever used.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>