Fix std::__unique name conflict with libstdc++ (#334)
std::__unique is defined in GNU C++ Library (/include/c++/11/bits/stl_algo.h). This leads to the following error:

error: "__unique" has already been declared in the current scope