Address -Wpragma-clang-attribute (#2297)
When building stdexec with Clang and libc++ version 23+,
`-Wpragma-clang-attribute` causes many errors that look like this:
```
error: unused attribute '__visibility__' in '#pragma clang attribute
push' region [-Werror,-Wpragma-clang-attribute]
```
attributable to uses of the `STDEXEC_NAMESPACE_STD_BEGIN` macro. stdexec
only uses that macro to forward-declare non-functions, and the attribute
is only applicable to functions, so the warning fires on every region
where stdexec forward-declares things in `std`.

This diff addresses the problem by modifying the
`STDEXEC_NAMESPACE_STD_BEGIN`/`_END` macros to push and pop a
`-Wno-pragma-clang-attribute` setting around the region whenever
building with Clang and libc++. GCC also fails when building with libc++
version 23+, but the failure is because GCC doesn't recognize the
`#pragma clang attribute push` pragma and so fails with an
unsuppressable warning-as-error; the tip of `main` in libc++ resolves
this problem by only emitting the pragma when compiling with Clang.

Co-authored-by: Eric Niebler <eniebler@nvidia.com>